// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AllSymbolChartsData, AllSymbolChartsErrors, AllSymbolChartsResponses, CleanEmptyRunsData, CleanEmptyRunsResponses, CompareRunsData, CompareRunsErrors, CompareRunsResponses, DeleteRunData, DeleteRunErrors, DeleteRunResponses, EventStatsData, EventStatsResponses, EventTimelineData, EventTimelineErrors, EventTimelineResponses, ExportTradesData, ExportTradesErrors, ExportTradesResponses, GetEventData, GetEventErrors, GetEventResponses, HealthData, HealthResponses, ListEventsData, ListEventsErrors, ListEventsResponses, ListRelationsData, ListRelationsErrors, ListRelationsResponses, ListRunsData, ListRunsResponses, RefreshSectorsData, RefreshSectorsResponses, RunAuditEventData, RunAuditEventErrors, RunAuditEventResponses, RunDailyReturnsData, RunDailyReturnsErrors, RunDailyReturnsResponses, RunDashboardData, RunDashboardErrors, RunDashboardResponses, RunEquityData, RunEquityErrors, RunEquityResponses, RunRiskData, RunRiskErrors, RunRiskResponses, RunSignalsData, RunSignalsErrors, RunSignalsResponses, RunSummaryData, RunSummaryErrors, RunSummaryResponses, RunTradesData, RunTradesErrors, RunTradesResponses, ServeSpaFullPathGetData, ServeSpaFullPathGetErrors, ServeSpaFullPathGetResponses, StartResearchData, StartResearchErrors, StartResearchResponses, SymbolChartData2, SymbolChartErrors, SymbolChartResponses, SymbolDetailData, SymbolDetailErrors, SymbolDetailResponses, SymbolFinancialsData, SymbolFinancialsErrors, SymbolFinancialsResponses, SymbolNamesData, SymbolNamesErrors, SymbolNamesResponses, TradedSymbolsData, TradedSymbolsErrors, TradedSymbolsResponses, TriggerEventInferenceData, TriggerEventInferenceErrors, TriggerEventInferenceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Runs
 */
export const listRuns = <ThrowOnError extends boolean = false>(options?: Options<ListRunsData, ThrowOnError>): RequestResult<ListRunsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListRunsResponses, unknown, ThrowOnError>({ url: '/api/runs', ...options });

/**
 * Clean Empty Runs
 *
 * 删除无效回测运行（带 test 标签/空跑/错误/沉寂孤儿）的审计数据。
 *
 * 孤儿口径带 30 分钟新鲜度护栏（见 analyzer.get_empty_or_error_runs），
 * 正在运行的回测不会被误删。响应按实际成功删除数统计（个别 run 可能
 * 在列出后被并发删除，delete_run 返回 0 不计入）。
 */
export const cleanEmptyRuns = <ThrowOnError extends boolean = false>(options?: Options<CleanEmptyRunsData, ThrowOnError>): RequestResult<CleanEmptyRunsResponses, unknown, ThrowOnError> => (options?.client ?? client).delete<CleanEmptyRunsResponses, unknown, ThrowOnError>({ url: '/api/runs/clean', ...options });

/**
 * Delete Run
 *
 * 删除指定回测运行的所有审计日志。
 *
 * 带生产标签（RUN_START payload.tags 含 'prod'）的 run 默认拒绝删除
 * （409），须显式 ``force=true`` 才允许删除，保护 ADR-005 可追溯链。
 */
export const deleteRun = <ThrowOnError extends boolean = false>(options: Options<DeleteRunData, ThrowOnError>): RequestResult<DeleteRunResponses, DeleteRunErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRunResponses, DeleteRunErrors, ThrowOnError>({ url: '/api/runs/{run_id}', ...options });

/**
 * Run Summary
 */
export const runSummary = <ThrowOnError extends boolean = false>(options: Options<RunSummaryData, ThrowOnError>): RequestResult<RunSummaryResponses, RunSummaryErrors, ThrowOnError> => (options.client ?? client).get<RunSummaryResponses, RunSummaryErrors, ThrowOnError>({ url: '/api/runs/{run_id}/summary', ...options });

/**
 * Run Equity
 */
export const runEquity = <ThrowOnError extends boolean = false>(options: Options<RunEquityData, ThrowOnError>): RequestResult<RunEquityResponses, RunEquityErrors, ThrowOnError> => (options.client ?? client).get<RunEquityResponses, RunEquityErrors, ThrowOnError>({ url: '/api/runs/{run_id}/equity', ...options });

/**
 * Run Trades
 */
export const runTrades = <ThrowOnError extends boolean = false>(options: Options<RunTradesData, ThrowOnError>): RequestResult<RunTradesResponses, RunTradesErrors, ThrowOnError> => (options.client ?? client).get<RunTradesResponses, RunTradesErrors, ThrowOnError>({ url: '/api/runs/{run_id}/trades', ...options });

/**
 * Run Audit Event
 *
 * 按 trace_id 返回审计事件完整记录（含原始 payload，供归因链点击下钻）。
 */
export const runAuditEvent = <ThrowOnError extends boolean = false>(options: Options<RunAuditEventData, ThrowOnError>): RequestResult<RunAuditEventResponses, RunAuditEventErrors, ThrowOnError> => (options.client ?? client).get<RunAuditEventResponses, RunAuditEventErrors, ThrowOnError>({ url: '/api/runs/{run_id}/audit/{trace_id}', ...options });

/**
 * Run Signals
 */
export const runSignals = <ThrowOnError extends boolean = false>(options: Options<RunSignalsData, ThrowOnError>): RequestResult<RunSignalsResponses, RunSignalsErrors, ThrowOnError> => (options.client ?? client).get<RunSignalsResponses, RunSignalsErrors, ThrowOnError>({ url: '/api/runs/{run_id}/signals', ...options });

/**
 * Run Dashboard
 */
export const runDashboard = <ThrowOnError extends boolean = false>(options: Options<RunDashboardData, ThrowOnError>): RequestResult<RunDashboardResponses, RunDashboardErrors, ThrowOnError> => (options.client ?? client).get<RunDashboardResponses, RunDashboardErrors, ThrowOnError>({ url: '/api/runs/{run_id}/dashboard', ...options });

/**
 * Run Risk
 */
export const runRisk = <ThrowOnError extends boolean = false>(options: Options<RunRiskData, ThrowOnError>): RequestResult<RunRiskResponses, RunRiskErrors, ThrowOnError> => (options.client ?? client).get<RunRiskResponses, RunRiskErrors, ThrowOnError>({ url: '/api/runs/{run_id}/risk', ...options });

/**
 * Run Daily Returns
 */
export const runDailyReturns = <ThrowOnError extends boolean = false>(options: Options<RunDailyReturnsData, ThrowOnError>): RequestResult<RunDailyReturnsResponses, RunDailyReturnsErrors, ThrowOnError> => (options.client ?? client).get<RunDailyReturnsResponses, RunDailyReturnsErrors, ThrowOnError>({ url: '/api/runs/{run_id}/daily_returns', ...options });

/**
 * Traded Symbols
 */
export const tradedSymbols = <ThrowOnError extends boolean = false>(options: Options<TradedSymbolsData, ThrowOnError>): RequestResult<TradedSymbolsResponses, TradedSymbolsErrors, ThrowOnError> => (options.client ?? client).get<TradedSymbolsResponses, TradedSymbolsErrors, ThrowOnError>({ url: '/api/runs/{run_id}/symbols', ...options });

/**
 * All Symbol Charts
 */
export const allSymbolCharts = <ThrowOnError extends boolean = false>(options: Options<AllSymbolChartsData, ThrowOnError>): RequestResult<AllSymbolChartsResponses, AllSymbolChartsErrors, ThrowOnError> => (options.client ?? client).get<AllSymbolChartsResponses, AllSymbolChartsErrors, ThrowOnError>({ url: '/api/runs/{run_id}/symbol_charts', ...options });

/**
 * Symbol Chart
 */
export const symbolChart = <ThrowOnError extends boolean = false>(options: Options<SymbolChartData2, ThrowOnError>): RequestResult<SymbolChartResponses, SymbolChartErrors, ThrowOnError> => (options.client ?? client).get<SymbolChartResponses, SymbolChartErrors, ThrowOnError>({ url: '/api/runs/{run_id}/symbol/{symbol}/chart', ...options });

/**
 * Export Trades
 */
export const exportTrades = <ThrowOnError extends boolean = false>(options: Options<ExportTradesData, ThrowOnError>): RequestResult<ExportTradesResponses, ExportTradesErrors, ThrowOnError> => (options.client ?? client).get<ExportTradesResponses, ExportTradesErrors, ThrowOnError>({ url: '/api/runs/{run_id}/export', ...options });

/**
 * Compare Runs
 */
export const compareRuns = <ThrowOnError extends boolean = false>(options: Options<CompareRunsData, ThrowOnError>): RequestResult<CompareRunsResponses, CompareRunsErrors, ThrowOnError> => (options.client ?? client).post<CompareRunsResponses, CompareRunsErrors, ThrowOnError>({
    url: '/api/compare',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Symbol Names
 *
 * 批量获取标的中文名。
 *
 * 优先从 DuckDB 缓存 instrument_details 表读取；
 * 缓存未命中的标的回退到 xtquant get_instrument_detail 实时获取。
 */
export const symbolNames = <ThrowOnError extends boolean = false>(options?: Options<SymbolNamesData, ThrowOnError>): RequestResult<SymbolNamesResponses, SymbolNamesErrors, ThrowOnError> => (options?.client ?? client).get<SymbolNamesResponses, SymbolNamesErrors, ThrowOnError>({ url: '/api/symbols/names', ...options });

/**
 * Symbol Detail
 *
 * 获取单个标的的详情（公司信息弹窗用）。
 *
 * 优先从 DuckDB 缓存读取；缓存未命中或 industry 为空时回退到
 * xtquant get_instrument_detail + THY1/DY1 板块批量补充。
 */
export const symbolDetail = <ThrowOnError extends boolean = false>(options: Options<SymbolDetailData, ThrowOnError>): RequestResult<SymbolDetailResponses, SymbolDetailErrors, ThrowOnError> => (options.client ?? client).get<SymbolDetailResponses, SymbolDetailErrors, ThrowOnError>({ url: '/api/symbols/{symbol}/detail', ...options });

/**
 * Refresh Sectors
 *
 * 手动触发行业+地区批量回填（通过 xtquant THY1/DY1 板块）。
 *
 * 重置进程内标记，允许下一次请求重新执行批量回填。
 */
export const refreshSectors = <ThrowOnError extends boolean = false>(options?: Options<RefreshSectorsData, ThrowOnError>): RequestResult<RefreshSectorsResponses, unknown, ThrowOnError> => (options?.client ?? client).post<RefreshSectorsResponses, unknown, ThrowOnError>({ url: '/api/symbols/refresh-sectors', ...options });

/**
 * Symbol Financials
 *
 * 获取标的历年财务数据（用于前端可视化）。
 */
export const symbolFinancials = <ThrowOnError extends boolean = false>(options: Options<SymbolFinancialsData, ThrowOnError>): RequestResult<SymbolFinancialsResponses, SymbolFinancialsErrors, ThrowOnError> => (options.client ?? client).get<SymbolFinancialsResponses, SymbolFinancialsErrors, ThrowOnError>({ url: '/api/symbols/{symbol}/financials', ...options });

/**
 * List Events
 */
export const listEvents = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>): RequestResult<ListEventsResponses, ListEventsErrors, ThrowOnError> => (options?.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({ url: '/api/events', ...options });

/**
 * Event Stats
 */
export const eventStats = <ThrowOnError extends boolean = false>(options?: Options<EventStatsData, ThrowOnError>): RequestResult<EventStatsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<EventStatsResponses, unknown, ThrowOnError>({ url: '/api/events/stats', ...options });

/**
 * Event Timeline
 */
export const eventTimeline = <ThrowOnError extends boolean = false>(options?: Options<EventTimelineData, ThrowOnError>): RequestResult<EventTimelineResponses, EventTimelineErrors, ThrowOnError> => (options?.client ?? client).get<EventTimelineResponses, EventTimelineErrors, ThrowOnError>({ url: '/api/events/timeline', ...options });

/**
 * List Relations
 */
export const listRelations = <ThrowOnError extends boolean = false>(options?: Options<ListRelationsData, ThrowOnError>): RequestResult<ListRelationsResponses, ListRelationsErrors, ThrowOnError> => (options?.client ?? client).get<ListRelationsResponses, ListRelationsErrors, ThrowOnError>({ url: '/api/events/relations', ...options });

/**
 * Get Event
 */
export const getEvent = <ThrowOnError extends boolean = false>(options: Options<GetEventData, ThrowOnError>): RequestResult<GetEventResponses, GetEventErrors, ThrowOnError> => (options.client ?? client).get<GetEventResponses, GetEventErrors, ThrowOnError>({ url: '/api/events/{sid}', ...options });

/**
 * Trigger Event Inference
 *
 * 触发事件推理管线。
 */
export const triggerEventInference = <ThrowOnError extends boolean = false>(options: Options<TriggerEventInferenceData, ThrowOnError>): RequestResult<TriggerEventInferenceResponses, TriggerEventInferenceErrors, ThrowOnError> => (options.client ?? client).post<TriggerEventInferenceResponses, TriggerEventInferenceErrors, ThrowOnError>({
    url: '/api/events/trigger',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start Research
 *
 * 触发策略研究（REST 入口，通过 WebSocket 广播进度）。
 */
export const startResearch = <ThrowOnError extends boolean = false>(options: Options<StartResearchData, ThrowOnError>): RequestResult<StartResearchResponses, StartResearchErrors, ThrowOnError> => (options.client ?? client).post<StartResearchResponses, StartResearchErrors, ThrowOnError>({
    url: '/api/research/start',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Serve Spa
 */
export const serveSpaFullPathGet = <ThrowOnError extends boolean = false>(options: Options<ServeSpaFullPathGetData, ThrowOnError>): RequestResult<ServeSpaFullPathGetResponses, ServeSpaFullPathGetErrors, ThrowOnError> => (options.client ?? client).get<ServeSpaFullPathGetResponses, ServeSpaFullPathGetErrors, ThrowOnError>({ url: '/{full_path}', ...options });
