// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * Benchmark
 *
 * 基准指标（取自 MARKET_DATA 载荷）。
 */
export type Benchmark = {
    /**
     * Alpha
     */
    alpha?: number;
    /**
     * Beta
     */
    beta?: number;
    /**
     * Information Ratio
     */
    information_ratio?: number;
    /**
     * Tracking Error
     */
    tracking_error?: number;
    /**
     * Benchmark Return
     */
    benchmark_return?: number;
};

/**
 * CleanRunsResponse
 *
 * DELETE /api/runs/clean
 */
export type CleanRunsResponse = {
    /**
     * Deleted Runs
     */
    deleted_runs: number;
    /**
     * Deleted Records
     */
    deleted_records: number;
};

/**
 * CompareRequest
 *
 * POST /api/compare
 */
export type CompareRequest = {
    /**
     * Run Ids
     */
    run_ids: Array<string>;
};

/**
 * CompareResponse
 *
 * POST /api/compare
 */
export type CompareResponse = {
    /**
     * Comparison
     */
    comparison: Array<CompareRow>;
};

/**
 * CompareRow
 *
 * 多策略对比指标行。
 */
export type CompareRow = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Total Return
     */
    total_return?: number;
    /**
     * Annual Return
     */
    annual_return?: number;
    /**
     * Annual Volatility
     */
    annual_volatility?: number;
    /**
     * Sharpe Ratio
     */
    sharpe_ratio?: number;
    /**
     * Max Drawdown
     */
    max_drawdown?: number;
    /**
     * Max Drawdown Duration Days
     */
    max_drawdown_duration_days?: number;
    /**
     * Var 95
     */
    var_95?: number;
    /**
     * Var 99
     */
    var_99?: number;
    /**
     * Cvar 95
     */
    cvar_95?: number;
    /**
     * Trade Count
     */
    trade_count?: number;
};

/**
 * DailyReturnPoint
 *
 * 日收益率采样点。
 */
export type DailyReturnPoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Portfolio Value
     */
    portfolio_value?: number;
    /**
     * Daily Return
     */
    daily_return?: number | null;
};

/**
 * DailyReturnsResponse
 *
 * GET /api/runs/{run_id}/daily_returns
 */
export type DailyReturnsResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Daily Returns
     */
    daily_returns: Array<DailyReturnPoint>;
};

/**
 * DashboardData
 *
 * GET /api/runs/{run_id}/dashboard
 */
export type DashboardData = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Total Events
     */
    total_events?: number;
    /**
     * Event Breakdown
     */
    event_breakdown?: {
        [key: string]: number;
    };
    /**
     * Time Range
     */
    time_range?: {
        [key: string]: string;
    };
    /**
     * Equity Curve
     */
    equity_curve?: Array<EquityPoint>;
    /**
     * Trade Journal
     */
    trade_journal?: Array<TradeRecord>;
    /**
     * Signal History
     */
    signal_history?: Array<SignalHistoryItem>;
    benchmark?: Benchmark;
    risk_metrics?: RiskMetrics;
    /**
     * Traded Symbols
     */
    traded_symbols?: Array<string>;
};

/**
 * DeleteRunResponse
 *
 * DELETE /api/runs/{run_id}
 */
export type DeleteRunResponse = {
    /**
     * Deleted Run Id
     */
    deleted_run_id: string;
    /**
     * Deleted Records
     */
    deleted_records: number;
};

/**
 * EquityPoint
 *
 * 权益曲线采样点。
 */
export type EquityPoint = {
    /**
     * Time
     */
    time: string;
    /**
     * Value
     */
    value: number;
};

/**
 * EquityResponse
 *
 * GET /api/runs/{run_id}/equity
 */
export type EquityResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Equity Curve
     */
    equity_curve: Array<EquityPoint>;
};

/**
 * EventDetail
 *
 * GET /api/events/{sid} — 事件详情 + 关联关系。
 */
export type EventDetail = {
    /**
     * Sid
     */
    sid: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sentiment
     */
    sentiment?: string;
    /**
     * Symbols
     */
    symbols?: Array<string>;
    /**
     * Category
     */
    category?: string;
    /**
     * Confidence
     */
    confidence?: number;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Conflict Group
     */
    conflict_group?: string | null;
    /**
     * Keys
     */
    keys?: Array<string>;
    /**
     * Source
     */
    source?: string;
    /**
     * Relations
     */
    relations?: Array<RelationItem>;
};

/**
 * EventItem
 *
 * 事件物质条目。
 */
export type EventItem = {
    /**
     * Sid
     */
    sid: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sentiment
     */
    sentiment?: string;
    /**
     * Symbols
     */
    symbols?: Array<string>;
    /**
     * Category
     */
    category?: string;
    /**
     * Confidence
     */
    confidence?: number;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Conflict Group
     */
    conflict_group?: string | null;
    /**
     * Keys
     */
    keys?: Array<string>;
    /**
     * Source
     */
    source?: string;
};

/**
 * EventStats
 *
 * GET /api/events/stats
 */
export type EventStats = {
    /**
     * Total Events
     */
    total_events?: number;
    /**
     * Total Relations
     */
    total_relations?: number;
    /**
     * By Sentiment
     */
    by_sentiment?: {
        [key: string]: number;
    };
    /**
     * By Category
     */
    by_category?: {
        [key: string]: number;
    };
    /**
     * Top Symbols
     */
    top_symbols?: Array<TopSymbol>;
};

/**
 * EventsResponse
 *
 * GET /api/events
 */
export type EventsResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Events
     */
    events?: Array<EventItem>;
};

/**
 * FinancialsResponse
 *
 * GET /api/symbols/{symbol}/financials
 */
export type FinancialsResponse = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Financials
     */
    financials?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * GET /api/health
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * PricePoint
 *
 * 日线行情采样点（开高低收量）。
 */
export type PricePoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Open
     */
    open?: number | null;
    /**
     * High
     */
    high?: number | null;
    /**
     * Low
     */
    low?: number | null;
    /**
     * Close
     */
    close?: number | null;
    /**
     * Volume
     */
    volume?: number;
};

/**
 * RelationItem
 *
 * 影响关系物质条目。
 */
export type RelationItem = {
    /**
     * Sid
     */
    sid: string;
    /**
     * Content
     */
    content: string;
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Target
     */
    target?: string;
    /**
     * Relation Type
     */
    relation_type?: string;
    /**
     * Direction
     */
    direction?: string;
    /**
     * Confidence
     */
    confidence?: number;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * RelationsResponse
 *
 * GET /api/events/relations
 */
export type RelationsResponse = {
    /**
     * Count
     */
    count: number;
    /**
     * Relations
     */
    relations?: Array<RelationItem>;
};

/**
 * ResearchStartRequest
 *
 * POST /api/research/start
 */
export type ResearchStartRequest = {
    /**
     * Idea
     */
    idea: string;
    /**
     * Max Rounds
     */
    max_rounds?: number;
    /**
     * Max Iterations
     */
    max_iterations?: number;
    /**
     * Min Improvement
     */
    min_improvement?: number;
};

/**
 * ResearchStartResponse
 *
 * POST /api/research/start
 */
export type ResearchStartResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Idea
     */
    idea: string;
    /**
     * Max Rounds
     */
    max_rounds: number;
    /**
     * Max Iterations
     */
    max_iterations: number;
};

/**
 * RiskMetrics
 *
 * 风险指标集合。
 */
export type RiskMetrics = {
    /**
     * Total Return
     */
    total_return?: number;
    /**
     * Annual Return
     */
    annual_return?: number;
    /**
     * Annual Volatility
     */
    annual_volatility?: number;
    /**
     * Sharpe Ratio
     */
    sharpe_ratio?: number;
    /**
     * Max Drawdown
     */
    max_drawdown?: number;
    /**
     * Max Drawdown Duration Days
     */
    max_drawdown_duration_days?: number;
    /**
     * Var 95
     */
    var_95?: number;
    /**
     * Var 99
     */
    var_99?: number;
    /**
     * Cvar 95
     */
    cvar_95?: number;
};

/**
 * RiskResponse
 *
 * GET /api/runs/{run_id}/risk
 */
export type RiskResponse = {
    /**
     * Run Id
     */
    run_id: string;
    risk_metrics: RiskMetrics;
};

/**
 * RunInfo
 *
 * 回测运行汇总条目。
 */
export type RunInfo = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Started
     */
    started: string;
    /**
     * Total Return
     */
    total_return?: number;
    /**
     * Sharpe
     */
    sharpe?: number;
    /**
     * Trade Count
     */
    trade_count?: number;
    /**
     * Event Count
     */
    event_count?: number;
    /**
     * Strategy Id
     */
    strategy_id?: string;
};

/**
 * RunSummaryItem
 *
 * RUN_END 审计统计条目。
 */
export type RunSummaryItem = {
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Count
     */
    count: number;
};

/**
 * RunSummaryResponse
 *
 * GET /api/runs/{run_id}/summary
 */
export type RunSummaryResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Summary
     */
    summary: Array<RunSummaryItem>;
};

/**
 * RunsResponse
 *
 * GET /api/runs
 */
export type RunsResponse = {
    /**
     * Runs
     */
    runs: Array<RunInfo>;
};

/**
 * SectorStatsResponse
 *
 * POST /api/symbols/refresh-sectors 与板块统计。
 */
export type SectorStatsResponse = {
    /**
     * Total
     */
    total?: number;
    /**
     * With Industry
     */
    with_industry?: number;
    /**
     * With Region
     */
    with_region?: number;
};

/**
 * SignalHistoryItem
 *
 * SIGNAL 事件历史条目。
 *
 * ``signals`` 为策略输出的信号字典（P1-13 后为结构化 JSON）；
 * 兼容历史数据中可能遗留的字符串序列化形式。
 */
export type SignalHistoryItem = {
    /**
     * Time
     */
    time: string;
    /**
     * Signals
     */
    signals?: {
        [key: string]: number;
    } | string;
};

/**
 * SignalsResponse
 *
 * GET /api/runs/{run_id}/signals
 */
export type SignalsResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Signals
     */
    signals: Array<SignalHistoryItem>;
};

/**
 * SymbolChartData
 *
 * GET /api/runs/{run_id}/symbol/{symbol}/chart
 */
export type SymbolChartData = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Price History
     */
    price_history?: Array<PricePoint>;
    /**
     * Trade Points
     */
    trade_points?: Array<TradePoint>;
};

/**
 * SymbolChartsResponse
 *
 * GET /api/runs/{run_id}/symbol_charts
 */
export type SymbolChartsResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Symbols
     */
    symbols: number;
    /**
     * Charts
     */
    charts?: Array<SymbolChartData>;
};

/**
 * SymbolNamesResponse
 *
 * GET /api/symbols/names
 */
export type SymbolNamesResponse = {
    /**
     * Names
     */
    names?: {
        [key: string]: string;
    };
};

/**
 * SymbolsResponse
 *
 * GET /api/runs/{run_id}/symbols
 */
export type SymbolsResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Symbols
     */
    symbols: Array<string>;
};

/**
 * TimelinePoint
 *
 * 事件时间线按天聚合条目。
 */
export type TimelinePoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Count
     */
    count?: number;
    /**
     * Positive
     */
    positive?: number;
    /**
     * Negative
     */
    negative?: number;
    /**
     * Neutral
     */
    neutral?: number;
};

/**
 * TimelineResponse
 *
 * GET /api/events/timeline
 */
export type TimelineResponse = {
    /**
     * Timeline
     */
    timeline?: Array<TimelinePoint>;
};

/**
 * TopSymbol
 *
 * 热门标的统计。
 */
export type TopSymbol = {
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Count
     */
    count: number;
};

/**
 * TradePoint
 *
 * 成交标注点。
 */
export type TradePoint = {
    /**
     * Time
     */
    time: string;
    /**
     * Direction
     */
    direction: string;
    /**
     * Price
     */
    price?: number;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Amount
     */
    amount?: number;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * TradeRecord
 *
 * 交易日志条目（FILL 事件）。
 */
export type TradeRecord = {
    /**
     * Time
     */
    time: string;
    /**
     * Trace Id
     */
    trace_id: string;
    /**
     * Symbol
     */
    symbol: string;
    /**
     * Type
     */
    type: string;
    /**
     * Price
     */
    price?: number;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Portfolio Value
     */
    portfolio_value?: number;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * TradesResponse
 *
 * GET /api/runs/{run_id}/trades
 */
export type TradesResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Trades
     */
    trades: Array<TradeRecord>;
};

/**
 * TriggerRequest
 *
 * POST /api/events/trigger
 */
export type TriggerRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * TriggerResponse
 *
 * POST /api/events/trigger
 */
export type TriggerResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ListRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runs';
};

export type ListRunsResponses = {
    /**
     * Successful Response
     */
    200: RunsResponse;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type CleanEmptyRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/runs/clean';
};

export type CleanEmptyRunsResponses = {
    /**
     * Successful Response
     */
    200: CleanRunsResponse;
};

export type CleanEmptyRunsResponse = CleanEmptyRunsResponses[keyof CleanEmptyRunsResponses];

export type DeleteRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}';
};

export type DeleteRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRunError = DeleteRunErrors[keyof DeleteRunErrors];

export type DeleteRunResponses = {
    /**
     * Successful Response
     */
    200: DeleteRunResponse;
};

export type DeleteRunResponse2 = DeleteRunResponses[keyof DeleteRunResponses];

export type RunSummaryData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/summary';
};

export type RunSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunSummaryError = RunSummaryErrors[keyof RunSummaryErrors];

export type RunSummaryResponses = {
    /**
     * Successful Response
     */
    200: RunSummaryResponse;
};

export type RunSummaryResponse2 = RunSummaryResponses[keyof RunSummaryResponses];

export type RunEquityData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/equity';
};

export type RunEquityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunEquityError = RunEquityErrors[keyof RunEquityErrors];

export type RunEquityResponses = {
    /**
     * Successful Response
     */
    200: EquityResponse;
};

export type RunEquityResponse = RunEquityResponses[keyof RunEquityResponses];

export type RunTradesData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/trades';
};

export type RunTradesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunTradesError = RunTradesErrors[keyof RunTradesErrors];

export type RunTradesResponses = {
    /**
     * Successful Response
     */
    200: TradesResponse;
};

export type RunTradesResponse = RunTradesResponses[keyof RunTradesResponses];

export type RunSignalsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/signals';
};

export type RunSignalsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunSignalsError = RunSignalsErrors[keyof RunSignalsErrors];

export type RunSignalsResponses = {
    /**
     * Successful Response
     */
    200: SignalsResponse;
};

export type RunSignalsResponse = RunSignalsResponses[keyof RunSignalsResponses];

export type RunDashboardData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/dashboard';
};

export type RunDashboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunDashboardError = RunDashboardErrors[keyof RunDashboardErrors];

export type RunDashboardResponses = {
    /**
     * Successful Response
     */
    200: DashboardData;
};

export type RunDashboardResponse = RunDashboardResponses[keyof RunDashboardResponses];

export type RunRiskData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/risk';
};

export type RunRiskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunRiskError = RunRiskErrors[keyof RunRiskErrors];

export type RunRiskResponses = {
    /**
     * Successful Response
     */
    200: RiskResponse;
};

export type RunRiskResponse = RunRiskResponses[keyof RunRiskResponses];

export type RunDailyReturnsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/daily_returns';
};

export type RunDailyReturnsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunDailyReturnsError = RunDailyReturnsErrors[keyof RunDailyReturnsErrors];

export type RunDailyReturnsResponses = {
    /**
     * Successful Response
     */
    200: DailyReturnsResponse;
};

export type RunDailyReturnsResponse = RunDailyReturnsResponses[keyof RunDailyReturnsResponses];

export type TradedSymbolsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/symbols';
};

export type TradedSymbolsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TradedSymbolsError = TradedSymbolsErrors[keyof TradedSymbolsErrors];

export type TradedSymbolsResponses = {
    /**
     * Successful Response
     */
    200: SymbolsResponse;
};

export type TradedSymbolsResponse = TradedSymbolsResponses[keyof TradedSymbolsResponses];

export type AllSymbolChartsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/symbol_charts';
};

export type AllSymbolChartsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AllSymbolChartsError = AllSymbolChartsErrors[keyof AllSymbolChartsErrors];

export type AllSymbolChartsResponses = {
    /**
     * Successful Response
     */
    200: SymbolChartsResponse;
};

export type AllSymbolChartsResponse = AllSymbolChartsResponses[keyof AllSymbolChartsResponses];

export type SymbolChartData2 = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
        /**
         * Symbol
         */
        symbol: string;
    };
    query?: never;
    url: '/api/runs/{run_id}/symbol/{symbol}/chart';
};

export type SymbolChartErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SymbolChartError = SymbolChartErrors[keyof SymbolChartErrors];

export type SymbolChartResponses = {
    /**
     * Successful Response
     */
    200: SymbolChartData;
};

export type SymbolChartResponse = SymbolChartResponses[keyof SymbolChartResponses];

export type ExportTradesData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Format
         */
        format?: string;
    };
    url: '/api/runs/{run_id}/export';
};

export type ExportTradesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportTradesError = ExportTradesErrors[keyof ExportTradesErrors];

export type ExportTradesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CompareRunsData = {
    body: CompareRequest;
    path?: never;
    query?: never;
    url: '/api/compare';
};

export type CompareRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareRunsError = CompareRunsErrors[keyof CompareRunsErrors];

export type CompareRunsResponses = {
    /**
     * Successful Response
     */
    200: CompareResponse;
};

export type CompareRunsResponse = CompareRunsResponses[keyof CompareRunsResponses];

export type SymbolNamesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Symbols
         */
        symbols?: string;
    };
    url: '/api/symbols/names';
};

export type SymbolNamesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SymbolNamesError = SymbolNamesErrors[keyof SymbolNamesErrors];

export type SymbolNamesResponses = {
    /**
     * Successful Response
     */
    200: SymbolNamesResponse;
};

export type SymbolNamesResponse2 = SymbolNamesResponses[keyof SymbolNamesResponses];

export type SymbolDetailData = {
    body?: never;
    path: {
        /**
         * Symbol
         */
        symbol: string;
    };
    query?: never;
    url: '/api/symbols/{symbol}/detail';
};

export type SymbolDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SymbolDetailError = SymbolDetailErrors[keyof SymbolDetailErrors];

export type SymbolDetailResponses = {
    /**
     * Response Symbol Detail
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SymbolDetailResponse = SymbolDetailResponses[keyof SymbolDetailResponses];

export type RefreshSectorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/symbols/refresh-sectors';
};

export type RefreshSectorsResponses = {
    /**
     * Successful Response
     */
    200: SectorStatsResponse;
};

export type RefreshSectorsResponse = RefreshSectorsResponses[keyof RefreshSectorsResponses];

export type SymbolFinancialsData = {
    body?: never;
    path: {
        /**
         * Symbol
         */
        symbol: string;
    };
    query?: never;
    url: '/api/symbols/{symbol}/financials';
};

export type SymbolFinancialsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SymbolFinancialsError = SymbolFinancialsErrors[keyof SymbolFinancialsErrors];

export type SymbolFinancialsResponses = {
    /**
     * Successful Response
     */
    200: FinancialsResponse;
};

export type SymbolFinancialsResponse = SymbolFinancialsResponses[keyof SymbolFinancialsResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Symbol
         */
        symbol?: string | null;
        /**
         * Sentiment
         */
        sentiment?: string | null;
        /**
         * Category
         */
        category?: string | null;
    };
    url: '/api/events';
};

export type ListEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    /**
     * Successful Response
     */
    200: EventsResponse;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type EventStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events/stats';
};

export type EventStatsResponses = {
    /**
     * Successful Response
     */
    200: EventStats;
};

export type EventStatsResponse = EventStatsResponses[keyof EventStatsResponses];

export type EventTimelineData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/events/timeline';
};

export type EventTimelineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventTimelineError = EventTimelineErrors[keyof EventTimelineErrors];

export type EventTimelineResponses = {
    /**
     * Successful Response
     */
    200: TimelineResponse;
};

export type EventTimelineResponse = EventTimelineResponses[keyof EventTimelineResponses];

export type ListRelationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Target
         */
        target?: string | null;
        /**
         * Direction
         */
        direction?: string | null;
    };
    url: '/api/events/relations';
};

export type ListRelationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRelationsError = ListRelationsErrors[keyof ListRelationsErrors];

export type ListRelationsResponses = {
    /**
     * Successful Response
     */
    200: RelationsResponse;
};

export type ListRelationsResponse = ListRelationsResponses[keyof ListRelationsResponses];

export type GetEventData = {
    body?: never;
    path: {
        /**
         * Sid
         */
        sid: string;
    };
    query?: never;
    url: '/api/events/{sid}';
};

export type GetEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    /**
     * Successful Response
     */
    200: EventDetail;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type TriggerEventInferenceData = {
    body: TriggerRequest;
    path?: never;
    query?: never;
    url: '/api/events/trigger';
};

export type TriggerEventInferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerEventInferenceError = TriggerEventInferenceErrors[keyof TriggerEventInferenceErrors];

export type TriggerEventInferenceResponses = {
    /**
     * Successful Response
     */
    200: TriggerResponse;
};

export type TriggerEventInferenceResponse = TriggerEventInferenceResponses[keyof TriggerEventInferenceResponses];

export type StartResearchData = {
    body: ResearchStartRequest;
    path?: never;
    query?: never;
    url: '/api/research/start';
};

export type StartResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartResearchError = StartResearchErrors[keyof StartResearchErrors];

export type StartResearchResponses = {
    /**
     * Successful Response
     */
    200: ResearchStartResponse;
};

export type StartResearchResponse = StartResearchResponses[keyof StartResearchResponses];

export type ServeSpaFullPathGetData = {
    body?: never;
    path: {
        /**
         * Full Path
         */
        full_path: string;
    };
    query?: never;
    url: '/{full_path}';
};

export type ServeSpaFullPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServeSpaFullPathGetError = ServeSpaFullPathGetErrors[keyof ServeSpaFullPathGetErrors];

export type ServeSpaFullPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
